from __future__ import annotations
from datetime import datetime
from typing import Protocol, Sequence
from .domain import *

class TgGateway(Protocol):
    async def list_tracked_dialogs(self) -> Sequence[DialogRef]: ...
    async def fetch_since(self, dialog: DialogRef, last_id: int, limit: int) -> Sequence[TgMessage]: ...
    async def download_media(self, message: TgMessage) -> Sequence[DownloadedMedia]: ...
    async def post_as_user(self, dialog_id: str, text: str) -> int: ...
    async def close(self) -> None: ...

class MailIn(Protocol):
    def poll(self) -> Sequence[InboundMail]: ...

class MailOut(Protocol):
    def compose_batch(self, batch: DialogBatch, media: dict[int, Sequence[DownloadedMedia]]) -> Sequence[MailDraft]: ...
    def send(self, draft: MailDraft) -> SentMail: ...
    def send_notice(self, subject: str, body: str) -> str: ...

class Clock(Protocol):
    def now(self) -> datetime: ...

class Store(Protocol):
    def get_cursor(self, dialog: DialogRef) -> Cursor: ...
    def advance_cursor(self, dialog: DialogRef, high_watermark: int) -> None: ...
    def commit_delivery(self, dialog: DialogRef, sent: Sequence[SentMail], high_watermark: int) -> None: ...
    def ledger_dialog(self, message_ids: Sequence[str]) -> str | None: ...
    def is_bridge_message(self, message_ids: Sequence[str]) -> bool: ...
    def record_notice_sent(self, message_id: str) -> None: ...
    def is_consumed(self, mail_ref: str) -> bool: ...
    def commit_reply(self, mail_ref: str, dialog_id: str, posted_msg_id: int) -> None: ...
